from django.urls import path
from .views import (CustomerView, CustomerDetailView,
                    CustomerRegistrationView, DashboardView, DashboardPageView,
                    StudentView, StudentListView, StudentAddView, StudentEditView,
                    StudentDetailView, UpdateRolePageView, UpdateRoleView, ProfileView,
                    ProfileDataView, CustomerListView, CustomerEditView, UserView, RolesView,
                    CustomerAddView, DocumentView, GetAllDocuments, GetAlStudentView, GetAllCustomers,
                    DashboardCountsView, RegistrationDataView, RegistrationPart1, RegistrationPart2,
                    ChildRegistration, ChildRegistration, ChildsList, ChildEditView, ChildEditWithIdView,
                    CustomerListForBooking, OrderSummaryForPreschool, CustomerId, StudentDetailsByCustomer,
                    SubmitPaymentRequest, DecryptionOfPayment, StudentCourseGroupDataView, AllStudentDetails,
                    CustomerStudentCount, StudentCourseDetailData, RoleForCoachView)

urlpatterns = [
    path('customer/register/', CustomerRegistrationView.as_view(),
         name="customer_registration"),
    path('parents/', CustomerListView.as_view(), name="parents"),
    path('customer_add/', CustomerAddView.as_view(), name="customer_add"),
    path('customers_edit/<int:pk>',
         CustomerEditView.as_view(), name="customers_edit"),
    path('customers/', CustomerView.as_view(), name="customers"),
    path('users/', UserView.as_view(), name="users"),
    path('roles/', RolesView.as_view(), name="roles"),
    path('roles_for_coach_dropdown/', RoleForCoachView.as_view(), name="roles_for_coach_dropdown"),
    path('customers/<int:pk>', CustomerDetailView.as_view(),
         name="customer_details"),
    path('student_list/', StudentListView.as_view(), name="student_list"),
    path('student_add/', StudentAddView.as_view(), name="student_add"),
    path('student_edit/', StudentEditView.as_view(), name="student_edit"),
    path('students/', StudentView.as_view(), name="student"),
    path('get_all_students/', GetAlStudentView.as_view(), name="get_all_student"),
    path('students/<int:pk>', StudentDetailView.as_view(), name="student_details"),
    path('dashboard/', DashboardView.as_view(), name="dashboard"),
    path('dashboard_page/', DashboardPageView.as_view(), name="dashboard_page"),
    path('update_role_page/', UpdateRolePageView.as_view(), name="update_role_page"),
    path('update_role/', UpdateRoleView.as_view(), name="update_role"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('profile_data/', ProfileDataView.as_view(), name="profile_data"),
    path('document/', DocumentView.as_view(), name="document"),
    path('get_all_documents/', GetAllDocuments.as_view(), name="get_all_documents"),
    path('get_all_customers/', GetAllCustomers.as_view(), name="get_all_customers"),
    path('dashboard_counts/', DashboardCountsView.as_view(),
         name="dashboard_counts"),
    path('registration_part1/', RegistrationPart1.as_view(),
         name="registration_part1"),
    path('registration_post/', RegistrationDataView.as_view(),
         name="registration_post"),
    path('registration_part2/', RegistrationPart2.as_view(),
         name="registration_part2"),
    path('child_registration/', ChildRegistration.as_view(),
         name="child_registration"),
    # path('child_registration/', ChildRegistration.as_view(), name="child_registration"),
    path('child_list/', ChildsList.as_view(), name="child_list/"),
    path('child_list_data/', ChildEditView.as_view(), name="child_list_data/"),
    path('child_list_data/<int:pk>',
         ChildEditWithIdView.as_view(), name="child_list_data/"),
    path('order_summary/', OrderSummaryForPreschool.as_view(), name="order_summary"),
    path('last_register_customer/', CustomerListForBooking.as_view(),
         name="last_register_customer"),
    path('customer_id_search/<str:pk>',
         CustomerId.as_view(), name="customer_id_search"),
    path('student_details_by_customer/<int:pk>',
         StudentDetailsByCustomer.as_view(), name="student_details_by_customer"),
    path('submit_payment/',
         SubmitPaymentRequest.as_view(), name="submit_payment"),
    path('payment_response',
         DecryptionOfPayment.as_view(), name="payment_response"),
     path('student_data_by_course_group_data/<int:pk>', StudentCourseGroupDataView.as_view(), name="student_data_by_course_group_data"),
     path('student_data/<int:pk>', AllStudentDetails.as_view(), name="student_data"),
     path('student_data/', AllStudentDetails.as_view(), name="student_data"),
     path('student_parent_count/', CustomerStudentCount.as_view(), name="student_parent_count"),
     path('student_with_course_type/<int:pk>/<int:dk>', StudentCourseDetailData.as_view(), name="student_with_course_type")
]
