from .account_record_view import *
from .course_booking_view import *
from .course_view import *
from .event_view import *
from .notification_view import *
from .cart_view import *
from .activity_view import *
from .chat_view import *
from .postcode_location_view import *