from django.urls import path
from .views import (CourseDetailView, CourseDataView, CourseDetailPageView,
                    CourseDetailDataPageView, FilteredCoursesView, FilteredCourseDataView,
                    CourseCartView, GetClassOnMonth, AddStudentToCourseView, BookCourseView, EventsForCoachView,
                    NotificationView, NotificationPageView, ExportBookedCourses, EventsForCustomerView, GetTokenView,
                    CoursesPageView, ManagementCourseView, ManagementCourseAddView, ManagementCourseEditView,
                    BookedCoursesList, BookedCoursePageView, BookedCourseDetailView, BookedCourseAddView,
                    BookedCoursesAddPage, BookedCourseEditView, StudentBookedView, CourseListingDataView,
                    GetBookedCoursesForCustomer, AccountRecordView, AccountRecordDataView, ShopView,
                    AddToCartView, UpdateCartView, CoursesPurchasedView, DeleteCartItem, RecentActivitiesView,
                    NotificationViewedView, UpcomingCoursesView, BookedEventsForCustomerView, ApproveCourseView,
                    ChatView, MessagesView, MessagesListView, ChatUsers, MessageDataView, InboxDataView,
                    ManagementCourseAddDataView, ChatHistoryView, ClassRegisterView, ClassRegisterDataView, course_booking,
                    CourseBookingList, course_booking1, BookingEditData, ManagementBookEditView, registration1,
                    CourseCategoryView, CourseCategoryDetailView, test_rota, GetCompany, GetLocation, GetCompaniesForDropdown,
                    CourseAvailableByFilterView, TestClassGroupData, BookingByCourseType, CheckForMemberForBookingCourseView,
                    ChildRegistrationForBookingCourseView, CustomerRegistrationForBookingCourseView, BookingByCourseTypeExceptPreschool,
                    RecentlyBookedStudents, BookingWithWeeks, GetDistanceByPostCode, CourseDetaiForAvailableSeatsView, AvailableSeatCalculater, 
                    EventWeekView, DayWiseWeekDetailsView, OrderView, OrderSummaryView, PriceMatrixDetails, PreschoolBookedDataSaveView,
                    SaveOrderDetailForCourseView, SaveOrderDetailForWeekView, ChildSelectionForPayment, StudentWithPaymentDoneView,LocationByCompany,
                    AllCompanyNamesViews, CourseEditFunctionalityView, GetAllVenuesByStatusOfCompletion, PriceMatricDynamicValueSaveView, 
                    PriceMatricDynamicValueForHolidaySaveView, CourseDetailDataByLocation)

urlpatterns = [
    path('shop/', ShopView.as_view(), name="shop"),
    path('courses/', CourseDetailView.as_view(), name="courses"),
    path('management_courses_data/', ManagementCourseView.as_view(),
         name="management_courses_data"),
    path('management_courses_add/', ManagementCourseAddView.as_view(),
         name="management_courses_add"),
    path('management_courses_add_data/', ManagementCourseAddDataView.as_view(),
         name="management_courses_add_data"),
    path('management_courses_edit_page/', ManagementCourseEditView.as_view(),
         name="management_courses_edit_page"),
    path('management_courses_edit/<int:pk>',
         ManagementCourseEditView.as_view(), name="management_courses_edit"),
    path('listing/', CoursesPageView.as_view(), name="listing"),
    path('course_data/', CourseDataView.as_view(), name="course_data"),
    path('approve_course/<int:pk>',
         ApproveCourseView.as_view(), name="approve_course"),
    path('course_listing_data/', CourseListingDataView.as_view(),
         name="course_listing_data"),
    path('course_description/<int:pk>',
         CourseDetailPageView.as_view(), name="course_detail"),
    path('course_detail_data/<int:pk>',
         CourseDetailDataPageView.as_view(), name="course_detail_data"),
    path('filtered_courses/<int:pk>/<id>',
         FilteredCoursesView.as_view(), name="filtered_courses"),
    path('filtered_course_data/<int:pk>/<id>/<month>',
         FilteredCourseDataView.as_view(), name="filtered_course_data"),
    path('get_class_on_month/', GetClassOnMonth.as_view(),
         name="get_class_on_month"),
    path('cart/', CourseCartView.as_view(), name="cart"),
    path('add_student_to_course/', AddStudentToCourseView.as_view(),
         name="add_student_to_course"),
    path('book_course/', BookCourseView.as_view(), name="book_course"),
    path('events_for_coach/', EventsForCoachView.as_view(), name="events_for_coach"),
    path('events_for_customer/', EventsForCustomerView.as_view(),
         name="events_for_customer"),
    path('booked_events_for_customer/', BookedEventsForCustomerView.as_view(),
         name="booked_events_for_customer"),
    path('messages/', NotificationPageView.as_view(), name="messages"),
    path('notifications_data/', NotificationView.as_view(),
         name="notifications_data"),
    path('notification_viewed/', NotificationViewedView.as_view(),
         name="notifications_viewed"),
    path('export_booked_classes/', ExportBookedCourses.as_view(),
         name="export_booked_classes"),
    path('get_tokens/', GetTokenView.as_view(), name="get_tokens"),
    path('booked_courses_page/', BookedCoursePageView.as_view(),
         name="booked_courses_page"),
    path('class_register/', ClassRegisterView.as_view(), name="class_register"),
    path('class_register_data/', ClassRegisterDataView.as_view(),
         name="class_register_data"),
    path('booked_courses_list/', BookedCoursesList.as_view(),
         name="booked_courses_list"),
    path('booked_courses_add_page/', BookedCoursesAddPage.as_view(),
         name="booked_courses_add_page"),
    path('book_courses_add/', BookedCourseAddView.as_view(),
         name="book_courses_add"),
    path('book_courses_edit/', BookedCourseEditView.as_view(),
         name="book_courses_edit"),
    path('book_course/<int:pk>',
         BookedCourseDetailView.as_view(), name="book_course"),
    path('student_booked/', StudentBookedView.as_view(), name="student_booked"),
    path('get_booked_courses_for_customer/', GetBookedCoursesForCustomer.as_view(),
         name="get_booked_courses_for_customer"),
    path('upcoming_courses/', UpcomingCoursesView.as_view(),
         name="upcoming_courses"),
    path('account_record/', AccountRecordView.as_view(), name="account_record"),
    path('account_record_data/', AccountRecordDataView.as_view(),
         name="account_record_data"),

    path('cart_add/', AddToCartView.as_view(), name="add_to_cart"),
    path('cart_update/', UpdateCartView.as_view(), name="update_cart"),
    path('cart_delete/<int:pk>', DeleteCartItem.as_view(), name="delete_cart"),
    path('get_purchased_courses/', CoursesPurchasedView.as_view(),
         name="get_purchased_courses"),
    # path('book_course_update/<int:pk>', CoachDetailView.as_view(), name="coach_detail"),
    path('recent_activities/', RecentActivitiesView.as_view(),
         name="recent_activity"),

    path('chat/', ChatView.as_view(), name='chat'),
    path('chat_users/', ChatUsers.as_view(), name='chat_users'),
    path('chat/<int:sender>/<int:receiver>/',
         MessagesView.as_view(), name='messages_view'),
    path('messages/<int:sender>/<int:receiver>/',
         MessageDataView.as_view(), name='messages_data_view'),
    path('api/messages/<int:sender>/<int:receiver>/',
         MessagesListView.as_view(), name='messages_list'),
    path('api/messages/', MessagesListView.as_view(), name='messages_list'),
    path('inbox_data/', InboxDataView.as_view(), name='inbox_data'),
    path('chat_history/<int:sender>/<int:receiver>/',
         ChatHistoryView.as_view(), name='chat_history'),
    path('bookings/', course_booking, name="bookings"),
    path('book/', CourseBookingList.as_view(), name="book"),
    path('books/', course_booking1, name='books'),
    path('edit_booking/<int:pk>', BookingEditData.as_view(), name='edit_booking'),
    path('management_book_edit_page/', ManagementBookEditView.as_view(),
         name='management_book_edit_page'),
    path('management_book_edit_page/<int:pk>',
         ManagementBookEditView.as_view(), name='management_book_edit_page'),
    path('course_category/', CourseCategoryView.as_view(), name="course_category/"),
    path('course_category_detail/<int:pk>',
         CourseCategoryDetailView.as_view(), name="course_category_detail"),
    path('registration1/', registration1, name='registration1'),
    path('get_company_name/<int:pk>',
         GetCompany.as_view(), name="get_company_name"),
     path('get_all_company_name/',
         AllCompanyNamesViews.as_view(), name="get_all_company_name"),
    path('get_location/<int:pk>', GetLocation.as_view(), name="get_location"),
    path('get_company_dropdown/<int:pk>',
         GetCompaniesForDropdown.as_view(), name="get_company_dropdown"),
    path('course_edit_by_venue/', CourseAvailableByFilterView.as_view(),
         name="available_courses"),
    path('test_course_group_data/', TestClassGroupData.as_view(),
         name="test_course_group_data"),
    path('booking_by_course_type_data/<int:pk>/<int:dk>',
         BookingByCourseType.as_view(), name="booking_by_course_type_data"),
    path('check_for_member/', CheckForMemberForBookingCourseView.as_view(),
         name="check_for_member/"),
    path('child_registration_for_booking/', ChildRegistrationForBookingCourseView.as_view(),
         name="child_registration_for_booking"),
    path('customer_registration_part_1/', CustomerRegistrationForBookingCourseView.as_view(),
         name="customer_registration_part_1"),
    path('booking_by_course_type_data_for_others/<int:pk>/<int:dk>',
         BookingByCourseTypeExceptPreschool.as_view(), name="booking_by_course_type_data_for_others"),
    path('recent_students/<int:pk>',
         RecentlyBookedStudents.as_view(), name="recent_students/"),
    path('week_booking/', BookingWithWeeks.as_view(), name="week_booking"),
    path("test_rotas/", test_rota.as_view()),
    path('get_distance_by_postcode/',
         GetDistanceByPostCode.as_view(), name="get_distance_by_postcode"),
    path('available_seats/', CourseDetaiForAvailableSeatsView.as_view(),
         name="available_seats"),
    path('calculated_seats/', AvailableSeatCalculater.as_view(),
         name='calculated_seats'),
    path('event_week/', EventWeekView.as_view(), name="event_week"),
    path('day_wise_week_details/', DayWiseWeekDetailsView.as_view(), name="day_wise_week_details"),
    path('order_for_booking/', OrderView.as_view(), name="order_for_booking"),
    path('order_summary_for_booking/', OrderSummaryView.as_view(), name="order_summary"),
    path('price_matrix/<int:pk>', PriceMatrixDetails.as_view(), name="price_matrix"),
    path('preschool_order_summary_submission/', PreschoolBookedDataSaveView.as_view(), name="preschool_order_summary_submission"),
    path('save_order_details/', SaveOrderDetailForCourseView.as_view(), name="save_order_details"),
    path('save_order_details_for_other_category/', SaveOrderDetailForWeekView.as_view(), name="save_order_details_for_other_category"),
    path('child_selection_for_payement/', ChildSelectionForPayment.as_view(), name="child_selection_for_payement"),
    path('student_with_payment_done/<int:pk>', StudentWithPaymentDoneView.as_view(), name="student_with_payment_done"),
    path('location_by_company/<int:dk>', LocationByCompany.as_view(), name="location_by_company"),
    path('course_edit_functionality/<int:pk>', CourseEditFunctionalityView.as_view(), name="course_edit_functionality"),
    path('get_venues_by_status/', GetAllVenuesByStatusOfCompletion.as_view(), name="get_venues_by_status"),
    path('price_matrix_for_saving_single_data/', PriceMatricDynamicValueSaveView.as_view(), name="price_matrix_for_saving_single_data"),
    path('course_detail_by_location/<int:pk>/<int:dk>', CourseDetailDataByLocation.as_view(), name="course_detail_by_location"),
    path('price_matrix_for_saving_holiday_data/', PriceMatricDynamicValueForHolidaySaveView.as_view(), name="price_matrix_for_saving_holiday_data")
]
